Work on editCourse
Kretsch-Matt/TaScheduler pull request #63
Opened 2024-04-30 20:31 UTC by Rorr4

Title.

2024-04-30 21:28 UTC, Kretsch-Matt requested changes

2024-04-30 21:28 UTC, Kretsch-Matt commented on scheduler/views.py
> +        if request.method == 'POST' and 'editCourseBtn' in request.POST:
It doesn't look like you have the latest views, and I think this is going to be a conflict. Can you pull and merge the latest code review into your branch? So then there wont be problems

2024-04-30 21:28 UTC, Kretsch-Matt commented on scheduler/views.py
> +        if request.method == 'POST' and 'editCourseBtn' in request.POST:
oh youre merging to master not code review, thats why its not showing there's conflicts

2024-04-30 21:29 UTC, Kretsch-Matt commented on scheduler/views.py
> +        if request.method == 'POST' and 'editCourseBtn' in request.POST:
i changed the pull request to code-review instead of master

2024-05-02 15:06 UTC, Kretsch-Matt approved these changes

2024-05-03 16:34 UTC, AndrewAlien approved these changes

2024-05-03 16:50 UTC, NathanEdwards2023 approved these changes
Looks good.

2024-05-10 15:00 UTC, merged